source = ~/.config/omarchy/current/theme/hyprlock.conf
 
general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = false
}

# Time 
label {
    monitor = 
    text = <span>$TIME</span>
    color = white
    position = 0, 350
    halign = center
    valign = center

    font_size = 200
    font_family = JetBrainsMono Nerd Font Mono

    shadow_passes = 1
    shadow_size = 8
    shadow_boost = 0.8
}

# Date
label {
    monitor = 
    text = cmd[update:1000] echo "$(date +"%A, %d %b %Y")"
    color = white
    position = 0, 190
    halign = center
    valign = center

    font_size = 25
    font_family = JetBrainsMono Nerd Font Mono Bold

    shadow_passes = 2
    shadow_size = 3
    shadow_boost = 1.5
}

# Battery
label {
    monitor = 
    text = cmd[update:1000] echo "$(~/scripts/battery-status.sh)"
    color = white
    position = 0, 140
    halign = center
    valign = center

    font_size = 18
    font_family = JetBrainsMono Nerd Font Mono Bold

    shadow_passes = 2
    shadow_size = 3
    shadow_boost = 1.5
}

input-field {
    monitor =
    size = 400, 66.67
    position = 0, -70
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 3

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
